name: RandomSpawn
author: reflexlabs
main: me.reflexlabs.randomspawn.RandomSpawn
version: 1.5
softdepend: [Essentials]
website: reflexLabs.com
api-version: 1.13
commands:
   randomspawn:
      description: main command of the plugin
      usage: /<command>
      aliases: [rs] 
permissions:
   randomspawn.*:
      description: unlocks all permissions (except reload/disable)
      default: op
   randomspawn.disable:
      description: permission to disable the random spawn ingame
      default: op
   randomspawn.list:
      description: permission to disable the random spawn ingame
      default: op
   randomspawn.create:
      description: permission to set new spawn points
      default: op
   randomspawn.remove:
      description: permission to remove spawn points
      default: op
   randomspawn.teleport:
      description: permission to teleport to spawn points
      default: op
   randomspawn.edit:
      description: permission to edit specific spawn points
      default: op   
   randomspawn.help:
      description: permission to view help menu
      default: true         